volumes:
  pg_data_production:
  static_volume:
  media_volume:
  frontend_build:

services:

  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: vovsn/foodgram_backend
    depends_on:
      - db
    env_file: .env
    volumes:
      - static_volume:/app/collected_static
      - media_volume:/app/media

  frontend:
    image: vovsn/foodgram_frontend
    depends_on:
      - backend
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/app/static
      - media_volume:/app/media