version: '3.3'
services:

  db:
    container_name: foodgram-db
    image: postgres:15
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    build: ../backend/foodgram
    restart: always
    depends_on:
      - db
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - static_volume:/app/collected_static
      - media_volume:/app/media
    ports:
      - "8000:8000"

  frontend:
    container_name: foodgram-front
    build: ../frontend
    depends_on:
      - backend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/app/collected_static
      - media_volume:/app/media

volumes:
  postgres_data:
  static_volume:
  media_volume:
