# Generated by Django 3.2.3 on 2025-02-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20250223_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(help_text='Введите количество ингредиента', verbose_name='Количество'),
        ),
    ]
