# Generated by Django 3.2.3 on 2025-02-23 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_foodgramuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgramuser',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
